### PR TITLE
Pngjs:Replace phantomjs dependency with chromium puppeteer 

### LINKED ISSUE #132: PhantomJS is an Unmaintained Project
Hello Team,

PhantomJS is an unmaintained project and pngjs uses phantomjs for its browser testing.

I am curious to know that will you be interested in replacing the phantomjs with some other suitable alternative, as it is better using up to date dependencies.

Please share your thoughts on this and any further suggestion regarding the phantomjs replacement.

### PR DESCRIPTION
**Pull request by ossdev07**
Phantomjs is an unmaintained project.So removed phantomjs dependency from package.json and run-compare.js. 
Added support for puppeteer to run the test suite on chrome.

Closes #132

### CODE REVIEW

**Comment by ossdev07** [comment]
Test-cases are failing on Node v6 because Puppeteer with async/await is only supported in Node v7.6.0 or greater.
Reference: https://www.npmjs.com/package/puppeteer
So as per our opinion, we should remove the Node v6 support and should add Node v12 support.
Kindly share your opinion as well.

**Comment by ossdev07** [comment]
Please can someone have a look at this PR.

**Comment by ossdev07** [comment]
Ping @lukeapage Could you please have a look at this PR and share your opinion.

**Comment by ossdev07** [comment]
@lukeapage Can you please have a look at this PR.

**Comment by ossdev07** [comment]
Hi @lukeapage , 
Kindly have a look at above PR. 
Thanks.

**Comment by lukeapage** [comment]
Sorry for the inexcusable lack of response..

**Comment by ossdev07** [comment]
Thanks for accepting this PR @lukeapage.

**Pull request merged**
