### PR TITLE
Transformations

### PR DESCRIPTION
**Pull request by tyler-g**
added `.flip` method for flipping image data horizontally or vertically.

Would like to add more transformation methods when time allows

### CODE REVIEW

**Comment by tyler-g** [comment]
anyone there?

**Comment by lukeapage** [comment]
Isn't this outside scope? It looks useful but I would put in a separate package..

**Comment by tyler-g** [comment]
Is it?  No problem to do that... I just thought it'd be nice to have one package that has transformations built-in.  There's already so many forks

**Comment by lukeapage** [comment]
I think so. Not in a fork, but in a new package e.g. image-transforms or image-transform-flip or whatever you would like to call it.

**Pull request closed without merging**
